// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/dakimura/migrent/ent/migration"
)

// Migration is the model entity for the Migration schema.
type Migration struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// AppliedAt holds the value of the "applied_at" field.
	AppliedAt time.Time `json:"applied_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Migration) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case migration.FieldID:
			values[i] = new(sql.NullInt64)
		case migration.FieldName:
			values[i] = new(sql.NullString)
		case migration.FieldAppliedAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Migration", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Migration fields.
func (m *Migration) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case migration.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			m.ID = int(value.Int64)
		case migration.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				m.Name = value.String
			}
		case migration.FieldAppliedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field applied_at", values[i])
			} else if value.Valid {
				m.AppliedAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Migration.
// Note that you need to call Migration.Unwrap() before calling this method if this Migration
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Migration) Update() *MigrationUpdateOne {
	return (&MigrationClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the Migration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Migration) Unwrap() *Migration {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Migration is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Migration) String() string {
	var builder strings.Builder
	builder.WriteString("Migration(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", name=")
	builder.WriteString(m.Name)
	builder.WriteString(", applied_at=")
	builder.WriteString(m.AppliedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Migrations is a parsable slice of Migration.
type Migrations []*Migration

func (m Migrations) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
