// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/dakimura/migrent/ent/migration"
)

// MigrationCreate is the builder for creating a Migration entity.
type MigrationCreate struct {
	config
	mutation *MigrationMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (mc *MigrationCreate) SetName(s string) *MigrationCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetAppliedAt sets the "applied_at" field.
func (mc *MigrationCreate) SetAppliedAt(t time.Time) *MigrationCreate {
	mc.mutation.SetAppliedAt(t)
	return mc
}

// SetNillableAppliedAt sets the "applied_at" field if the given value is not nil.
func (mc *MigrationCreate) SetNillableAppliedAt(t *time.Time) *MigrationCreate {
	if t != nil {
		mc.SetAppliedAt(*t)
	}
	return mc
}

// Mutation returns the MigrationMutation object of the builder.
func (mc *MigrationCreate) Mutation() *MigrationMutation {
	return mc.mutation
}

// Save creates the Migration in the database.
func (mc *MigrationCreate) Save(ctx context.Context) (*Migration, error) {
	var (
		err  error
		node *Migration
	)
	mc.defaults()
	if len(mc.hooks) == 0 {
		if err = mc.check(); err != nil {
			return nil, err
		}
		node, err = mc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MigrationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mc.check(); err != nil {
				return nil, err
			}
			mc.mutation = mutation
			node, err = mc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(mc.hooks) - 1; i >= 0; i-- {
			mut = mc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MigrationCreate) SaveX(ctx context.Context) *Migration {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (mc *MigrationCreate) defaults() {
	if _, ok := mc.mutation.AppliedAt(); !ok {
		v := migration.DefaultAppliedAt()
		mc.mutation.SetAppliedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MigrationCreate) check() error {
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New("ent: missing required field \"name\"")}
	}
	if v, ok := mc.mutation.Name(); ok {
		if err := migration.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if _, ok := mc.mutation.AppliedAt(); !ok {
		return &ValidationError{Name: "applied_at", err: errors.New("ent: missing required field \"applied_at\"")}
	}
	return nil
}

func (mc *MigrationCreate) sqlSave(ctx context.Context) (*Migration, error) {
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (mc *MigrationCreate) createSpec() (*Migration, *sqlgraph.CreateSpec) {
	var (
		_node = &Migration{config: mc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: migration.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: migration.FieldID,
			},
		}
	)
	if value, ok := mc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: migration.FieldName,
		})
		_node.Name = value
	}
	if value, ok := mc.mutation.AppliedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: migration.FieldAppliedAt,
		})
		_node.AppliedAt = value
	}
	return _node, _spec
}

// MigrationCreateBulk is the builder for creating many Migration entities in bulk.
type MigrationCreateBulk struct {
	config
	builders []*MigrationCreate
}

// Save creates the Migration entities in the database.
func (mcb *MigrationCreateBulk) Save(ctx context.Context) ([]*Migration, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Migration, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MigrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				mutation.done = true
				if err != nil {
					return nil, err
				}
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MigrationCreateBulk) SaveX(ctx context.Context) []*Migration {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
