// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/dakimura/migrent/ent/migration"
	"github.com/dakimura/migrent/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	migrationFields := schema.Migration{}.Fields()
	_ = migrationFields
	// migrationDescName is the schema descriptor for name field.
	migrationDescName := migrationFields[0].Descriptor()
	// migration.NameValidator is a validator for the "name" field. It is called by the builders before save.
	migration.NameValidator = migrationDescName.Validators[0].(func(string) error)
	// migrationDescAppliedAt is the schema descriptor for applied_at field.
	migrationDescAppliedAt := migrationFields[1].Descriptor()
	// migration.DefaultAppliedAt holds the default value on creation for the applied_at field.
	migration.DefaultAppliedAt = migrationDescAppliedAt.Default.(func() time.Time)
	// migration.UpdateDefaultAppliedAt holds the default value on update for the applied_at field.
	migration.UpdateDefaultAppliedAt = migrationDescAppliedAt.UpdateDefault.(func() time.Time)
}
